# Generated by Django 3.1.2 on 2020-12-12 18:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, _ and - are allowed', regex=re.compile('^[-\\w]+\\Z'))])),
                ('data_type', models.IntegerField(choices=[(1, 'Full Name'), (2, 'Job'), (3, 'Email'), (4, 'Company'), (5, 'Phone Number'), (6, 'Integer'), (7, 'Date')])),
                ('order', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('column_separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('\t', 'Tab (\t)'), (' ', 'Space ( )'), ('|', 'Pipe (|)')], max_length=1)),
                ('string_character', models.CharField(choices=[('"', 'Double Quote (")'), ("'", "Single Quote (')")], max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BigIntegerField()),
                ('end', models.BigIntegerField()),
                ('column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fakecsv.column')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='fakecsv/%Y-%m-%d')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakecsv.schema')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakecsv.schema'),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('schema', 'order')},
        ),
    ]
